# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163_oC-pCFA4hlDYY9nS4nBgiX4KR9XM8
"""

import pandas as pd
import numpy as np
import csv
!pip install pgmpy

from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

heart=pd.read_csv("heart (1).csv")

print(heart.head(5))

heart=heart.replace("?",np.nan)
print(heart.head(5))

print(heart.columns)

Model=BayesianModel([('age','trestbps'),('age','fbs'),('sex','trestbps'),('trestbps','target'),('fbs','target'),('target','ca'),('target','chol')])
print(Model)

Model.fit(heart,estimator=MaximumLikelihoodEstimator)
print(Model.get_cpds('age'))

heart_infer=VariableElimination(Model)
q=heart_infer.query(variables=["target"],evidence={'age':30})
print(q)

q=heart_infer.query(variables=['target'],evidence={'chol':100})
print(q)

