# -*- coding: utf-8 -*-
"""Backprop (4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G6Xoc-snaVNTlp4me8gBuk-R6qHySy06
"""

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.neural_network import MLPClassifier

iris=load_iris()
values=iris.data
target=iris.target

ss=StandardScaler()
values=ss.fit_transform(values)

values_train,values_test,target_train,target_test=train_test_split(values,target,test_size=0.3)

n = 1000
loss_cur = 999
classifier=MLPClassifier(hidden_layer_sizes=(4,3),activation='logistic',solver='sgd',learning_rate_init=0.5,warm_start=True,max_iter=1,random_state=1,verbose=True)
for _ in range(n):
    classifier.fit(values_train,target_train)
    loss_prev = loss_cur
    loss_cur= classifier.loss_
    for i in classifier.coefs_:
        print(i, end='\n\n')
    if abs(loss_cur - loss_prev) < 0.0001:
        break
target_pred=classifier.predict(values_test)

print(classifier.score(values_test,target_test))

for i in classifier.coefs_:
    print(i, end='\n\n')