# -*- coding: utf-8 -*-
"""bayesian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iy2l2cq3bUVizUyHeP9SItGLtlJtPsjz
"""

pip install pgmpy

import numpy as np
import csv
import pandas as pd
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

#read Heart Disease data
heartDisease = pd.read_csv('heart1.csv')
heartDisease = heartDisease.replace('?',np.nan)

#display the data
print('Few examples from the dataset are given below')
print(heartDisease.head())

heartDisease.describe()

heartDisease.columns

#Model Bayesian Network
model=BayesianModel([('age','trestbps'),('age','fbs'),
('sex','trestbps'),('exang','trestbps'),('trestbps','target'),('fbs','target'),('target','restecg'),
('target','thalach'),('target','chol')])

import networkx as nx
nx.draw(model, with_labels=True)

# Bayesian belief network

# sex   exang    age
#   \    |      /    \
#      trestbps      fbs
#        \        /
#          target
#        /     |     \
#  restecg  thalach   chol

#Learning CPDs using Maximum Likelihood Estimators
print('\n Learning CPD using Maximum likelihood estimators')
model.fit(heartDisease,estimator=MaximumLikelihoodEstimator)

# Inferencing with Bayesian Network
print('\n Inferencing with Bayesian Network:')
HeartDisease_infer = VariableElimination(model)

q = HeartDisease_infer.query(variables=['target'], evidence={
    'age':70,
    'sex':1,
    'trestbps':145,
    'chol':174,
    'fbs':0,
    'restecg':1,
    'thalach':125,
    'exang':1,
    })

print(q)